name: Validate OpenAPI specification

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install openapi-spec-validator
        run: |
          python -m pip install --upgrade pip
          pip install openapi-spec-validator
      - name: Validate OpenAPI document
        run: openapi-spec-validator openapi.yaml
